### ISSUE TITLE
Bridge casings interrupted by lower level roads

### ISSUE THREAD

**Issue by pnorman** [hotosm/HDM-CartoCSS#156]
![18/41580/89793](https://f.cloud.github.com/assets/1190866/1207206/2140d5ae-25b0-11e3-830e-7c7fb7cd3c92.png "18/41580/89793")

The bridge casing on the primary is interrupted by the tertiary road below, making it look like they connect.

**Comment by yohanboniface** [comment]
Should be fixed with latest deploy, can you  confirm?

**Comment by pnorman** [comment]
![89793](https://cloud.githubusercontent.com/assets/1190866/12005756/9f799a68-ab6a-11e5-96bd-dee949236d1c.png)

![44914](https://cloud.githubusercontent.com/assets/1190866/12005757/a4f79fbc-ab6a-11e5-8e13-f1617de31b03.png)
