### ISSUE TITLE
bridges for paths

### ISSUE THREAD

**Issue by xkomczax** [hotosm/HDM-CartoCSS#193]
Bridges are not rendered for highway=path; bridge=yes

**Comment by skorasaurus** [comment]
also fixed in the roads refactoring =) https://github.com/hotosm/HDM-CartoCSS/commit/1343d1d1ab697bf0b21e6b2071f24b26a5a8040a

**Comment by yohanboniface** [comment]
Good catch :)

**Comment by yohanboniface** [comment]
@skorasaurus just noticed you were not collaborator, and thus were not able to close issues not opened by you, very strange. Certainly linked to the team refactoring in Github rights management. Anyway, you are now back to be collaborator in this repository. :)
