### ISSUE TITLE
Possible to use with mod_tile?

### ISSUE THREAD

**Issue by mapmeld** [hotosm/HDM-CartoCSS#250]
I recently visited two schools in Haiti using [Internet in a Box](http://internet-in-a-box.org/) to view maps offline. I'd like to replace their default Mapnik tiles with the HOTOSM mapping layer. Their server currently renders tiles using [mod_tile](http://wiki.openstreetmap.org/wiki/Mod_tile).

Does CartoCSS in a way 'compile' to a static Mapnik XML file which could be used for mod_tile? Or would it be necessary to have them install TileMill or another CartoCSS-specific library?

**Comment by mapmeld** [comment]
Closing the issue - creating a mapnik.xml file turned out to be really simple:

```
git clone https://github.com/hotosm/HDM-CartoCSS
git clone https://github.com/mapbox/carto.git
cd carto
npm install
./bin/carto ../HDM-CartoCSS/project.mml > output_mapnik.xml
```

**Comment by yohanboniface** [comment]
Oh, damn, totally missed this issue. It's often that I miss Github notification and I still don't know why.
Anyway, cool if you finally made it, and sorry for not having answered.

**Comment by CrazyCoder4Carrot** [comment]
But there is only project.yml file rather than project.xml file.

**Comment by yohanboniface** [comment]
`carto project.yml > project.xml`
