### ISSUE TITLE
ST_Simplify / ST_Buffer on large polygons...

### ISSUE THREAD

**Issue by cquest** [hotosm/HDM-CartoCSS#252]
The rendering on admin boundary names uses ST_Buffer + ST_Simplify to offset names in two different layers:

https://github.com/hotosm/HDM-CartoCSS/blob/master/hdm.mml#L1200
https://github.com/hotosm/HDM-CartoCSS/blob/master/hdm.mml#L1226

It is causing high load when country polygons are involved as the ST_Buffer, then the ST_Simplify are computed on the country full polygon.

This could be replaced by text-dy on the original geometry (best option), or by replacing p.way by ST_Intersection(p.way,ST_Expand(!bbox!,128))

**Comment by yohanboniface** [comment]
Closed via #253.
