### ISSUE TITLE
Darkness at the zoom level 11 and 12

### ISSUE THREAD

**Issue by adam21** [hotosm/HDM-CartoCSS#260]
Hello everyone,

I installed the HDM-CartoCSS project, it works well except the pixelation (darkness) that can be seen at the zoom level 11 and 12, is this because of intersections between roads 
or it is an overlap ? 

How can I fix this?

Thank you in advance and excuse my english

![file](https://cloud.githubusercontent.com/assets/11215545/6397534/b0c8be02-bde5-11e4-90a5-2a85bc4d4e39.png)

**Comment by yohanboniface** [comment]
It's because of road intersections, see #1.
This needs a whole refactoring of the road styling, this is why it still open since a long time.

I'm closing here because there already is #1.
