### ISSUE TITLE
Render island names

### ISSUE THREAD

**Issue by bgirardot** [hotosm/HDM-CartoCSS#263]
I think I never see island names render at any zoom level in Vanuatu, which is not good.

**Comment by skorasaurus** [comment]
yep, it's on a TODO list; we should get around to it one of these days , already reported at #124

**Comment by bgirardot** [comment]
Sorry for not looking, just wanted to get it in before I forgot about in in the middle of merging some data. One of these days I'll have some time to see if I can help on this. I keep pointing people to the project for outreachy because it seems like an enjoyable and important project.
