### ISSUE TITLE
Iberian Peninsula is rendered as landuse=industrial

### ISSUE THREAD

**Issue by skorasaurus** [hotosm/HDM-CartoCSS#264]
from #262 ; Narrowed down that the only relation that the Spain, Portugal, Andorra share is the Iberian Peninsula relation - http://www.openstreetmap.org/relation/3870917#map=5/38.548/0.813&layers=H
I'm having trouble obtaining the relation's history but my guess is that the area=yes tag is the culprit.

**Comment by skorasaurus** [comment]
downloaded the entire relation in josm; josm validator gives: "Multipolygon relation should be tagged with area tags and not the outer ways"

**Comment by pavlo-dudka** [comment]
landuse=industrial and name="Puerto de Cartagena" should be removed from two ways: http://overpass-turbo.eu/s/8rU
It may be better to contact someone local to map Puerto de Cartagena correctly.

**Comment by skorasaurus** [comment]
I had taken another look at this later this morning and tried to compare and contrast this with the openstreetmap-carto style which has no such problems. 

There's 3 layers use in our stylesheet for landuse. 

2 of them: landuse_gen0 and landuse_gen1 have "geometry": "multipolygon"
https://github.com/hotosm/HDM-CartoCSS/blob/master/hdm.mml#L80

they're later used in base.mss as 

#landuse_gen0[zoom>3][zoom<=9],
#landuse_gen1[zoom>9][zoom<=12]


I originally thought this was the culprit as openstreetmap-carto does not list multipolygon as its geometry in any of its layers including its layer for landuse - landuse-overlay . 

But according to this logic, the Iberian peninsula should be covered as industrial at zoom 12 but it is not.

**Comment by skorasaurus** [comment]
I contacted a maintainer of the Iberian Peninsula relation and decided to remove the landuse=industrial tag from one of the peninsulas members (done in http://www.openstreetmap.org/changeset/30484528 ) 

The Peninsula is now slowly appearing correctly in our map layer. 

I'm leaving this issue open until we determine if we should change any of code to prevent this in the future. 

@pnorman : What's the decision in openstreetmap-carto to NOT use multipolygon as your geometry in any layer? We have them currently in 2 layers - https://github.com/hotosm/HDM-CartoCSS/blob/master/hdm.mml#L80

**Comment by pnorman** [comment]
> @pnorman : What's the decision in openstreetmap-carto to NOT use multipolygon as your geometry in any layer?

There are no multipolygons in the database.

**Comment by skorasaurus** [comment]
The cause of this rendering error was a tagging mistake. However, other rendering styles like  openstreetmap-carto and its German and French forks don't use multipolygon as any geometry values. 

My mapnik is rusty so I don't know why the landuse layers' geometry was first set to multipolygon instead of polygon. 

so, two questions: 

1. Should we then close this issue? 
2. Would changing our two landuse layers' geometries prevent these types of tagging mistakes appear in our stylesheet?

[I made those changes in my local HOT instance](https://github.com/skorasaurus/HDM-CartoCSS/commit/5094b644d15e28d0d419bdbd882d0a5f0aca98bb) of Haiti and compared it to the HOT layer on the server and did not see any changes or things broken.

**Comment by yohanboniface** [comment]
Interesting! Want to submit a PR so we "test" that in the prod servers?

**Comment by pnorman** [comment]
I really doubt this has anything to do with differing geometry types. In fact, given the `-G` in your [import instructions](https://github.com/hotosm/HDM-CartoCSS/wiki/Importing-data#import), you can expect these layers to return some MULTIPOLYGON types.

It looks to be a fairly simple case of a broken multipolygon. openstreetmap/osm2pgsql#52 is worth reviewing

**Comment by matkoniecz** [comment]
Problem seems to be gone.

**Comment by skorasaurus** [comment]
closing since the problem is gone :)
