### ISSUE TITLE
Hard-coded paths in hdm.mml

### ISSUE THREAD

**Issue by bradh** [hotosm/HDM-CartoCSS#269]
The contour_line and hillshade data sources in hdm.mml are hard-coded (e.g. "file": "/home/ybon/OSM/SRTM/haiti_contour_25m.shp"). 

Ideally that would be pointed to the right source automatically.

As a minimum, how to modify the configuration should be included in https://github.com/hotosm/HDM-CartoCSS/wiki/Download-DEM

**Comment by yohanboniface** [comment]
If you use Tilemill, you should use [cartocc](https://github.com/hotosm/HDM-CartoCSS/wiki/Use-with-Tilemill#local-configuration).
If you use Kosmtik, you should have a [localconfig file](https://github.com/hotosm/HDM-CartoCSS/wiki/Open-with-Kosmtik#local-config).

**Comment by bradh** [comment]
OK, I made a wiki edit for Kosmtik that might make this a bit obvious for new users.
