### ISSUE TITLE
highway=raceway is unusually prominent

### ISSUE THREAD

**Issue by mapmeld** [hotosm/HDM-CartoCSS#271]
A way marked highway=raceway is too prominent in the HOTOSM tile layer:

On this park map it is #000 black and thick. It sticks out a lot more than, for example, a playground boundary
![screen shot 2015-06-12 at 4 06 01 pm](https://cloud.githubusercontent.com/assets/643918/8141523/f39a8b40-111c-11e5-997b-95231397d9b7.png)

You can see a black dot even at very low zooms:
![screen shot 2015-06-12 at 4 03 58 pm](https://cloud.githubusercontent.com/assets/643918/8141499/b1d644ce-111c-11e5-8dff-1a34ec2e7790.png)

**Comment by skorasaurus** [comment]
thanks for this catch! 

I'll take a look and fix it tomorrow; I believe this shouldn't be rendered at all.

**Comment by skorasaurus** [comment]
It's not the raceway tag alone; but the combination of highway=raceway and surface= 
http://www.openstreetmap.org/way/304502539#map=19/47.91011/106.91915&layers=HD

highway=raceway alone does not result in the black line. (Example in Haiti)[www.openstreetmap.org/way/51174665#map=17/19.43010/-72.20773&layers=H]
