### ISSUE TITLE
*_link roads are now rendered as black

### ISSUE THREAD

**Issue by skorasaurus** [hotosm/HDM-CartoCSS#272]
While investigating #271 today, my local instance was displaying all highways tagged as *_link  (including primary_link, secondary_link) as black. 

[This was introduced by the most recent commit](https://github.com/hotosm/HDM-CartoCSS/commit/a650d2a69c7b5b99b4789fc3a23ad3a33cb0c1f9)

I tested it out on [the older commit](https://github.com/hotosm/HDM-CartoCSS/commit/15a5cd36c43b00e9fb1598d8e5b22ae1fdd08b08) and *_link highways were rendered as intended. 

Here's what Dominican republic looks like: 
![selection_006](https://cloud.githubusercontent.com/assets/955351/8504224/694ac6f0-219b-11e5-9bd1-9a58c2c7121b.png)

I've viewed several of those roads and the only common tag among all of them is the highway=*_link tag.

**Comment by yohanboniface** [comment]
Good catch! I've reverted. We don't really care about rendering non standard xxx_link at the end.
