### ISSUE TITLE
Add documentation on how to setup stylesheet without a DEM

### ISSUE THREAD

**Issue by pnorman** [hotosm/HDM-CartoCSS#274]
For development purposes, hillshading is not always required. 

It would be good to be able to set up the stylesheet with an empty DEM or provide an empty hillshading file

**Comment by yohanboniface** [comment]
You can add `active: false` on the layers through localconfig. I'll add a mention and an example for that :)

**Comment by yohanboniface** [comment]
Added in https://github.com/hotosm/HDM-CartoCSS/wiki/Open-With-Kosmtik#download-and-preprocess-dem
