### ISSUE TITLE
List required dependencies for install

### ISSUE THREAD

**Issue by pnorman** [hotosm/HDM-CartoCSS#275]
So far I've found the install process needs these, beyond the normal postgis/osm2pgsql database and mapnik-based rendering server

* bash
* wget
* unzip
* gdal
* shapeindex from mapnik

**Comment by yohanboniface** [comment]
Added in https://github.com/hotosm/HDM-CartoCSS/wiki/Importing-data

It's a wiki, so you don't even need to ask to edit it ;)
