### ISSUE TITLE
Is the a way to obtain Mapnik style

### ISSUE THREAD

**Issue by seb49** [hotosm/HDM-CartoCSS#276]
Hello,

I'm on windows, it's not easy to work with OSM data and tools.

I'm able to build tile with mapnik and his default style. I'd like to do the same with HOT style but can't generate it.

Regards

**Comment by skorasaurus** [comment]
Hi, 

Congratulations for being able to build tiles with mapnik alone that can be difficult.

In my experience and many others, it is often easier to work with TileMill and edit the MSS files than editing mapnik's XML files. 
You can also try using Kosmtik - https://github.com/kosmtik/kosmtik

If you need to convert CartoCSS to mapnik XML, you'll have to install the carto binary - https://github.com/mapbox/carto

Unfortunately, I don't think there is a converter from mapnik XML to CartoCSS.

**Comment by seb49** [comment]
I think I was not clear,

I can build tile from osm data with mapnik but with the "default" style not HOT style
carto seem doesn't work, the file "xml" is empty and no error message

**Comment by seb49** [comment]
Finally I have installed mapnik on Ubuntu 14 virtual machine. But when I type
carto hdm.mml > hdm.xml
nothing happened (only the file hmd.xml was created but it is empty). I think I need some shp files and configure cartocci.json file but I don't know what SHP files I need and where to find them

**Comment by yohanboniface** [comment]
@seb49 see #277

**Comment by bradh** [comment]
I'm also trying to generate a mapnik XML file, but I'm a bit lost. The instructions at https://github.com/hotosm/HDM-CartoCSS/wiki/Open-with-Kosmtik refers to a MML that no longer exists (as of https://github.com/hotosm/HDM-CartoCSS/commit/8ecd59207f64f3651c4444f11ec6564559840a06)

I see the project.yml and I guess there is a pre-processing step that is needed before the carto step, but I'm not sure what it is.

**Comment by skorasaurus** [comment]
@bradh I saw your comment but it appears to have been deleted. Did you figure this out then?

@seb49 ; with Yohan's refactoring in several commits https://github.com/hotosm/HDM-CartoCSS/commit/f9088d03f9163306ebe7ad408ae4bd5a75b21e18 _https://github.com/hotosm/HDM-CartoCSS/commit/8604d963becdc153efffe8cd1b27dedc00472661 https://github.com/hotosm/HDM-CartoCSS/commit/1343d1d1ab697bf0b21e6b2071f24b26a5a8040a https://github.com/hotosm/HDM-CartoCSS/commit/45a0847d9d4e27f9624ceda1286a7834839b733a ,_  you should now be able to export the style to Mapnik XML if you open the project in kosmtik and select 'EXPORT' XML option in its GUI.  

Re-open if you're still unable to export in kosmtik.

**Comment by yohanboniface** [comment]
> if you open the project in kosmtik and select 'EXPORT' XML option in its GUI. 

You can also do that via the command line, with something like:

    node index.js export --format xml

Use `node index.js export --help` to get more options.

**Comment by bradh** [comment]
Yep, I figured it out. Always the way, just after I post...
