### ISSUE TITLE
national park boundaries

### ISSUE THREAD

**Issue by porjo** [hotosm/HDM-CartoCSS#278]
If national park boundaries are to be included, then they should sit on top of other styles. At the moment things like `landuse=wood` obscure the boundaries e.g.

Normal OSM layer showing national park boundary:
![screenshot from 2015-11-03 08-52-22](https://cloud.githubusercontent.com/assets/1296987/10896839/4efa89ac-8208-11e5-8d83-fc1b76d0daef.png)

HOT map showing partial boundary:
![screenshot from 2015-11-03 08-51-48](https://cloud.githubusercontent.com/assets/1296987/10896835/4a14dc3a-8208-11e5-9bce-e4f1f5a11908.png)

**Comment by yohanboniface** [comment]
Thanks for the report: issue was that the contour line was same color as wooded landuses.

**Comment by porjo** [comment]
@yohanboniface this issue is still occuring e.g. http://www.openstreetmap.org/#map=15/-27.3664/152.1962&layers=H

Is the fix still in the process of being pushed out?

**Comment by yohanboniface** [comment]
Not yet pushed in production.
I was waiting for the green light here: #277 but I think now we are (ping @skorasaurus in case I'm wrong :) )
(Also I'm currently in Ethiopia with very little Internet, so I'll deal with that when I'm back in Paris, around 22th Dec.).
