### ISSUE TITLE
Not rendering every country capital in the map

### ISSUE THREAD

**Issue by naoliv** [hotosm/HDM-CartoCSS#281]
As we can see at https://www.openstreetmap.org/#map=5/-17.686/-58.491&layers=H not every country has its capital properly rendered in the map (with its name and a star):

![](https://cloud.githubusercontent.com/assets/982338/15988429/d648db44-3026-11e6-940e-df6dc786306e.png)

At least Brazil and Peru are missing it.

What exactly HDM is using to render them?

I was thinking that the criteria was a node with `admin_level=2` (since [Brasília](https://www.openstreetmap.org/node/34567423) lacks it), but [Lima](https://www.openstreetmap.org/node/4114700189) has it and isn't rendered too.

Whatever the criteria is, maybe there is some kind of problem with it?

**Comment by yohanboniface** [comment]
This is the bit of SQL:

    CASE WHEN capital='yes' AND admin_level='2' THEN 'country' ELSE NULL END AS is_capital

And a bit of context: https://github.com/hotosm/HDM-CartoCSS/pull/130

**Comment by skorasaurus** [comment]
Investigating this. 
Lima looks to be an odd case: It's place tag value is "neighbourhood;city"

**Comment by naoliv** [comment]
Is it possible to query the `admin_centre` node with `capital=yes` of the `admin_level=2` relation instead?

Specially Brasília, it's part of an `admin_level=2`, `admin_level=4` and an `admin_level=8`; while some people say that it should use the highest level (`admin_level=2`) in the node, I don't agree (as the relations are already properly representing the correct values).

**Comment by skorasaurus** [comment]
@naoliv are there any other capitals besides Lima et Brasilia that you don't see and expect to see?

**Comment by naoliv** [comment]
With a very quick look (so probably I am missing some countries) I found:

[Cockburn Town](https://www.openstreetmap.org/node/296255680) isn't displayed too (likewise Brasília, it lacks `admin_level=2`)

With [Montserrat](https://www.openstreetmap.org/relation/537257) I guess it will be another exception: [Plymouth](https://www.openstreetmap.org/node/677060125) has a `capital` role in the relation and [Brades](https://www.openstreetmap.org/node/358222806) the `admin_centre` role.
[Wikipedia](https://en.wikipedia.org/wiki/Montserrat) says that Plymouth is the _de jure_ capital and Brades the _de facto_ one. I don't know which one should be displayed (both?).

[Ouagadougou](https://www.openstreetmap.org/node/27565002) is `admin_centre` of [Burkina Faso](https://www.openstreetmap.org/relation/192783), but it has `admin_level=8`

[Porto-Novo](https://www.openstreetmap.org/node/1669842684) (`admin_centre` of [Benin](https://www.openstreetmap.org/relation/192784)) also lacks `admin_level=2`

[Abuja](https://www.openstreetmap.org/node/31203257) (`admin_centre` of [Nigeria](https://www.openstreetmap.org/relation/192787)) has `admin_level=2`, but isn't displayed, probably beucase it has `capital=2` instead `capital=yes`

[Vaiaku](https://www.openstreetmap.org/node/649015243) (from [Tuvalu](https://www.openstreetmap.org/relation/2177266) lacks `admin_level`)

[Dhaka](https://www.openstreetmap.org/node/3442474911) (from [Bangladesh](https://www.openstreetmap.org/relation/184640)) has `capital=2` and no `admin_level`

[Fakaofo](https://www.openstreetmap.org/node/3168342084) (from [Tokelau](https://www.openstreetmap.org/relation/2186600)) basically lacks everything, even a `name`

At least giving this very quick look, I guess that, if possible, querying for the `admin_centre` node of `admin_level=2` relations should give the most satisfactory results.

**Comment by Zalitoar** [comment]
Hi people! At Latin American OSM's group in Telegram, we were talking about this and we made some editions. we added to Brasilia, Asunción and Lima (capitals of Brasil, Paraguay and Peru) the admin_level=2 tag so we think that now they will appear as capitals.

**Comment by yohanboniface** [comment]
Seems like this can be closed.
Thanks @Zalitoar !
