### ISSUE TITLE
Airport icon on Humanitarian layer

### ISSUE THREAD

**Issue by LucieGueuning** [hotosm/HDM-CartoCSS#295]
The airport logo should be as obvious as on the standard layer (same level of zoom and same icon): https://www.openstreetmap.org/search?query=south%20kivu#map=12/-4.1117/29.0468; 
![image](https://user-images.githubusercontent.com/25951555/37408850-daaffe6c-2794-11e8-8fad-da89f24429ed.png)

instead of https://www.openstreetmap.org/search?query=south%20kivu#map=12/-4.1117/29.0039&layers=H 
![image](https://user-images.githubusercontent.com/25951555/37408910-00e7e482-2795-11e8-903a-7e6eacd702a3.png)

**Comment by yohanboniface** [comment]
So for now the rule is:
- if the airport has a iata field render from zoom 10
- else render from zoom 15

What changes would you suggest? :)

**Comment by LucieGueuning** [comment]
- iata field is perfect, keep it like that. thanks. 
- Render for regular airstrips to put visible at level 12 + change the icon (from standard one, the purple one)

**Comment by yohanboniface** [comment]
> regular airstrips to put visible at level 12

I'm not perfectly sure what you mean by "regular [airstrip](http://www.wordreference.com/enfr/airstrip)", so just to confirm: you suggest to render non IATA airfields starting at zoom 12, correct? :)

> + change the icon (from standard one, the purple one)

ATM, we have no coloured icon. I'd prefer not to create an exception on this. We may challenge this rule, but that's another (not that simple) story :)

**Comment by LucieGueuning** [comment]
1. correct
2. according to us, we should change the rule and opting for coloured one but as you said, that's another story. Let's keep it simple. 

Again, thank you very much for your inputs on that.
