### ISSUE TITLE
Health facilities on Humanitarian layer

### ISSUE THREAD

**Issue by LucieGueuning** [hotosm/HDM-CartoCSS#296]
Health facilities (hospital) need to be display , at level 14 as it is on the standard layer (15)
 (https://www.openstreetmap.org/search?query=south%20kivu#map=15/-4.1042/29.0864) 
![image](https://user-images.githubusercontent.com/25951555/37409170-8951d3c8-2795-11e8-8e7f-c466da92910c.png)

instead of https://www.openstreetmap.org/search?query=south%20kivu#map=14/-4.1073/29.0694&layers=H
![image](https://user-images.githubusercontent.com/25951555/37409256-cf720378-2795-11e8-9697-c65fa0a1a2f4.png)

**Comment by yohanboniface** [comment]
cf #299 should be good now.

**Comment by LucieGueuning** [comment]
It is not yet changed, normal?

**Comment by yohanboniface** [comment]
> It is not yet changed, normal?

Can you a bit more explicit? :)
A screenshot and a link to a map for example :)
I guess it's a cache issue, but it also can be something else ;)
For example, here it's changed:
https://www.openstreetmap.org/#map=18/18.55023/-72.30760&layers=H
![screenshot-20180320185505-1661x1401](https://user-images.githubusercontent.com/146023/37673340-3c8389ee-2c70-11e8-8f67-a424f35ebbe6.png)

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/37674161-1b002ab2-2c6a-11e8-8e13-662e0fef2afd.png)


https://www.openstreetmap.org/#map=17/18.55203/-72.31098&layers=H
