### ISSUE TITLE
health center need to be displayed as it is map by missing map

### ISSUE THREAD

**Issue by LucieGueuning** [hotosm/HDM-CartoCSS#299]

**Comment by Jorieke** [comment]
In our field mapping we are currently using: 

amenity=hospital 
amenity=clinic 
amenity=doctors

**Comment by yohanboniface** [comment]
Should be good for the hospital icon and for the clinic now rendered.
(Again, this will take some minutes/hours to be visible everywhere, cf tiles caching).
I'm closing here, let's continue on #300 for arbitrating zoom levels.
