### ISSUE TITLE
NGO office should be display as it is mapped by missing map

### ISSUE THREAD

**Issue by LucieGueuning** [hotosm/HDM-CartoCSS#301]

**Comment by Jorieke** [comment]
Currently mapped as office=ngo

**Comment by yohanboniface** [comment]
Should be fixed (it may take time to rerender all the tiles), see for example:

https://www.openstreetmap.org/#map=18/19.75547/-72.21212&layers=H

or for some NGO we have a dedicated icon (eg. Oxfam):

https://www.openstreetmap.org/node/2386179475
