### ISSUE TITLE
Name change not reflected

### ISSUE THREAD

**Issue by michael63-osm** [hotosm/HDM-CartoCSS#307]
This is an issue which was reported both in an OSM note (https://www.openstreetmap.org/note/1660337) as well as in an email to HOT Mapper support.

There are two objects which describe a campus of the Hamburg University of Technology
1. https://www.openstreetmap.org/way/152833048
2, https://www.openstreetmap.org/relation/3996052 which contains the way just mentioned

The name of this university was changed more than half a year ago in both objects by https://www.openstreetmap.org/changeset/60143186

The humanitarian tiles show the name on zoom levels 16 and 17 but they still show the previous name (specifiying the location as Hamburg-Harburg)

For zoom 17 the tile which displays the name is https://tile-c.openstreetmap.fr/hot/17/69165/42416.png
If I interpret its metadata correctly this has been regenerated at least today (I marked it as /dirty this morning to make sure it gets updated). If this turns out to be a general problem with polygons or relations which span several tiles then such a problem might occur in many places on this map.

**Comment by skorasaurus** [comment]
Thank you for the report. 

Sorry for the delay, but this appears to be now resolved.
