### ISSUE TITLE
Strange rendering because of new data on Russia sea

### ISSUE THREAD

**Issue by descl** [hotosm/HDM-CartoCSS#319]
Hello since 1 or 2 weeks I noticed on hotosm that there are strange squares that appeared above Russia:
![image](https://user-images.githubusercontent.com/1270023/89505115-63252b00-d7c9-11ea-90c0-609f12d028b9.png)
https://www.openstreetmap.org/#map=4/72.44/48.08&layers=H

After having struggled a lot I found the source of this squares: https://www.openstreetmap.org/relation/11285957#map=4/75.35/69.26&layers=H these data were added just a month ago on OSM and are visible directly on the basemap.
The data is very interesting and sad :( however I suppose that we do not want to see it on the "standard" basemap.

I admit that I find it difficult to know where to report this observation, I hope I am not in the wrong place. Thank you for everything you do it's great!

Christophe

**Comment by matkoniecz** [comment]
I would say that it is incorrect tagging.

This fits neither tag name (`landuse=landfill`) nor description at wiki ("A Landfill site (also known as a tip, dump, rubbish dump or dumping ground and historically as a midden) is a site for the disposal of waste materials by burial.") nor how this tag is usually used.

**Comment by skorasaurus** [comment]
This has been resolved; this was a tagging issue where landuse=landfill was being incorrectly used. ([disused:landuse](https://wiki.openstreetmap.org/wiki/Key:disused:landuse?uselang=en)[=landfill](https://wiki.openstreetmap.org/wiki/Tag:disused:landuse=landfill?uselang=en)
