### ISSUE TITLE
Dead URLs in project.yml ?

### ISSUE THREAD

**Issue by esgn** [hotosm/HDM-CartoCSS#320]
Hi,

I'm under the impression than the following URLs in project.yml :
* http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip
* http://data.openstreetmapdata.com/land-polygons-split-3857.zip

Should be replaced by :
* https://osmdata.openstreetmap.de/download/simplified-land-polygons-complete-3857.zip
* https://osmdata.openstreetmap.de/download/land-polygons-split-3857.zip

**Comment by skorasaurus** [comment]
Thanks for the correction; I've made a pull request to reflect this.
