### ISSUE TITLE
Broken roads system [BUG]

### ISSUE THREAD

**Issue by IvoBiaus** [hotosm/HDM-CartoCSS#338]
Hey i think that since yesterday i started noticing that in Portugal (at least this is the only location i checked) the Roads system is bugged, showing them all across the sector, displaying road that don't belong there since i have even encountered roads with Russian names in there.
I have noticed this happening at the zoom levels: 20 to 15, 13 and 11 (14 and 10 seemed fine).
I checked other layers and they seamed ok too, i only could replicate it (sometimes, not always) with the Cyclist layer.
I'm attaching a screenshot of what i see and a link that should display the same sector.
I have tried with multiple browsers, with incognito, my phone and even asked a friend 3000 km away to check, him and i got the same result everywhere.

Source: https://www.openstreetmap.org/#map=11/40.1740/-7.9267&layers=H

![image](https://github.com/hotosm/HDM-CartoCSS/assets/43274372/affa069f-60b6-4a63-87ef-db80621bc35c)
![image](https://github.com/hotosm/HDM-CartoCSS/assets/43274372/b32b52a8-265c-4334-a090-919951fabb01)

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting. This is the result of vandalism in OpenStreetMap; there have been increased acts of vandalism in recent weeks - https://community.openstreetmap.org/t/have-you-spotted-vandalism-on-openstreetmap-org/114684 & https://community.openstreetmap.org/t/the-osm-standard-tile-layer-looks-wrong-white-lines-abusive-comments-etc/111583/368 The malicious edits in OpenStreetMap appear to have been reverted (I checked 40.30100/-8.07725 for example, and features there match what's in bing) so the inaccurate and malicious edits no longer exist in OpenStreetMap's data. 


The hotosm layer is updated with the latest version of OpenStreetMap on a regular basis (I believe every 48 hours or so) and it will eventually reflect the improved OpenStreetMap data.
