### ISSUE TITLE
No highway names or numbers

### ISSUE THREAD

**Issue by Lonkmapp** [hotosm/HDM-CartoCSS#340]
The humanitarian map does not show any official highway names or labels on it such as I-10 or I-80 or I-95. Would love to see the highway names on the map since it’s such a beautiful map layer. Thank you

**Comment by Lonkmapp** [comment]
Please let me know what you can do

**Comment by Lonkmapp** [comment]
Please please please please let me know if you can fix this

**Comment by skorasaurus** [comment]
please see my response at https://github.com/hotosm/HDM-CartoCSS/issues/342#issuecomment-2560430915
