### ISSUE TITLE
No highway labels on humanitarian map

### ISSUE THREAD

**Issue by Lonkmapp** [hotosm/HDM-CartoCSS#341]
Can you add this so the map looks more professional  please !

**Comment by matkoniecz** [comment]
duplicate of https://github.com/hotosm/HDM-CartoCSS/issues/340

**Comment by skorasaurus** [comment]
Please see response at https://github.com/hotosm/HDM-CartoCSS/issues/342#issuecomment-2560430915

**Comment by Lonkmapp** [comment]
Oh wow so there is no way to add them in at all ?

**Comment by matkoniecz** [comment]
> Oh wow so there is no way to add them in at all ?

Response in https://github.com/hotosm/HDM-CartoCSS/issues/342#issuecomment-2560430915 is saying something else.

Please reread https://github.com/hotosm/HDM-CartoCSS/issues/342#issuecomment-2560430915

**Comment by Lonkmapp** [comment]
That’s truly disappointing :(
